# Generated by Django 5.2.11 on 2026-03-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_phone_profile_role_alter_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='leader_course',
            field=models.CharField(blank=True, choices=[('', '빈칸'), ('ING', '진행'), ('DONE', '완료'), ('GRAD', '수료')], default='', max_length=10, verbose_name='이끄미수료'),
        ),
        migrations.AddField(
            model_name='profile',
            name='leader_course_date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='이끄미수료일'),
        ),
        migrations.AddField(
            model_name='profile',
            name='leader_status',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='이끄미현황'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pungsam_cho',
            field=models.CharField(blank=True, choices=[('', '빈칸'), ('ING', '진행'), ('DONE', '완료'), ('GRAD', '수료')], default='', max_length=10, verbose_name='풍삶초'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pungsam_cho_date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='풍삶초 수료일'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pungsam_first',
            field=models.CharField(blank=True, choices=[('', '빈칸'), ('ING', '진행'), ('DONE', '완료'), ('GRAD', '수료')], default='', max_length=10, verbose_name='풍삶첫'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pungsam_first_date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='풍삶첫 수료일'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pungsam_gi',
            field=models.CharField(blank=True, choices=[('', '빈칸'), ('ING', '진행'), ('DONE', '완료'), ('GRAD', '수료')], default='', max_length=10, verbose_name='풍삶기'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pungsam_gi_date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='풍삶기 수료일'),
        ),
    ]
