# Generated by Django 5.2.11 on 2026-03-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_leader_course_profile_leader_course_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='leader_course',
            field=models.CharField(blank=True, choices=[('', '미진행'), ('ING', '진행'), ('DONE', '완료'), ('GRAD', '수료')], default='', max_length=10, verbose_name='이끄미수료'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pungsam_cho',
            field=models.CharField(blank=True, choices=[('', '미진행'), ('ING', '진행'), ('DONE', '완료'), ('GRAD', '수료')], default='', max_length=10, verbose_name='풍삶초'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pungsam_first',
            field=models.CharField(blank=True, choices=[('', '미진행'), ('ING', '진행'), ('DONE', '완료'), ('GRAD', '수료')], default='', max_length=10, verbose_name='풍삶첫'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pungsam_gi',
            field=models.CharField(blank=True, choices=[('', '미진행'), ('ING', '진행'), ('DONE', '완료'), ('GRAD', '수료')], default='', max_length=10, verbose_name='풍삶기'),
        ),
    ]
