# Generated by Django 5.2.11 on 2026-02-18 09:42

import approvals.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', '임시'), ('SUBMITTED', '상신'), ('IN_PROGRESS', '진행중'), ('REJECTED', '반려'), ('COMPLETED', '완료')], default='DRAFT', max_length=20)),
                ('current_line_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docs_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=approvals.models.attachment_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='approvals.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CONSULT', '협의'), ('APPROVE', '결재'), ('RECEIVE', '수신/열람')], max_length=10)),
                ('order', models.PositiveIntegerField()),
                ('decision', models.CharField(choices=[('PENDING', '대기'), ('APPROVED', '승인'), ('REJECTED', '반려'), ('READ', '열람')], default='PENDING', max_length=10)),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='approvals.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'order', 'id'],
            },
        ),
    ]
