# Generated by Django 5.2.11 on 2026-02-19 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentline',
            options={'ordering': ['order', 'id']},
        ),
    ]
